version: 2.1

jobs:
  build:
    docker:
      - image: python:3.11.0

    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            python src/rice_cooker_test.py
