version: 2.1

jobs:
  build:
    docker:
      - image: cimg/ruby:3.2.2
    steps:
      - checkout
      - run:
          name: Setup dependencies
          command: |
            gem install bundler
            bundle install
      - run:
          name: Display contents of src/constants/
          command: ls -R src/constants/
      - run:
          name: Run tests
          command: |
            rspec